#***********************************************************************************************************************
# * Projet: Phpmesure
# * Auteur: Tristan Fleury - tristan.fleury.gre@gmail.com
# * Année de production: 2017
# * Licence: GNU General Public License (GPL), version 3
# * Copyright © 2017 Tristan Fleury
# **********************************************************************************************************************/

viducphpmesureserveur_index:
    path:     /
    defaults: { _controller: viducphpmesureserveurBundle:Default:index }

viducphpmesureserveur_application:
    path:     /application/{application}
    defaults: { _controller: viducphpmesureserveurBundle:Default:application, application:null }