#/***********************************************************************************************************************
# * Projet: Phpmesure
# * Auteur: Tristan Fleury - tristan.fleury.gre@gmail.com
# * Année de production: 2017
# * Licence: GNU General Public License (GPL), version 3
# * Copyright © 2017 Tristan Fleury
# **********************************************************************************************************************/

services:
    #viducphpmesureserveur.test:
    #    class: viduc\phpmesureserveurBundle\Controller\DefaultController
    #    arguments: ["@service_container"]
